# baseurl = ""
baseurl = "https://www.loveway.one"
languageCode = "en-us"
title = "Love is the Way to One"
theme = "hugo-theme-learn-2.1.0"


[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  subtitle = "Claim Your Power Through Radical Self-Knowledge"
  author = "K.I. Loveway"

[outputs]
  home = [ "HTML", "RSS", "JSON"]


# "More" menu items
[[menu.shortcuts]] 
  name = "<i class='fa fa-github'></i> Github repo"
  identifier = "ds"
  url = "https://github.com/kreionloveway/loveway.one"
  weight = 10

[[menu.shortcuts]] 
  name = "Questions? Comments?<br /><img src='/img/email_white.png' width='220px'>"
  url = "mailto:?subject=Regarding%20Loveway.one"
  weight = 12